namespace Learning.Application.Models.Problems.Queries.GetStatistics.GetMonthlyProblemSubmissionsComparison;
public record GetMonthlyProblemSubmissionsComparisonQuery : IQuery<GetMonthlyProblemSubmissionsComparisonResult>;
public record GetMonthlyProblemSubmissionsComparisonResult(int CurrentMonthCount, int PreviousMonthCount, double PercentageChange);
