global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using User.Domain.Models;
global using User.Domain.ValueObjects;
global using User.Domain.Abstractions;
global using User.Application.Data.Repositories;
global using User.Application.Data;
global using User.Infrastructure.Data;
global using User.Application.Common;