namespace Learning.Application.Models.Courses.Queries.GetStatistics.GetMonthlyNewLearnersComparison;
public record GetMonthlyNewLearnersComparisonQuery: IQuery<GetMonthlyNewLearnersComparisonResult>;
public record GetMonthlyNewLearnersComparisonResult(int CurrentMonthCount, int PreviousMonthCount, double PercentageChange);

